events {}

http {
    include mime.types;
    default_type application/octet-stream;

    types {
        application/wasm wasm;
        application/javascript mjs;
    }

    server {
        listen 80 default_server;
        server_name _;

        root /var/www/web;
        index index.html;

        # Обработка API-запросов
        location /api/ {
            proxy_pass http://backend:5001/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # CORS для всех методов
        location / {
            # CORS
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            try_files $uri $uri/ /index.html;
        }

        # Оптимизация кеша для статики
        location ~* \.(?:wasm|dll|js|mjs|css|html|json|png|jpg|jpeg|gif|woff2?|ttf|svg|eot|ico|webp)$ {
            expires 1y;
            access_log off;
            add_header Cache-Control "public";
        }
    }
}
